### ISSUE TITLE
Error cliente-servidor

### ISSUE THREAD

**Issue by deivid2025** [DarkInventor/easy-ui#2]
Hola como estas,

Encuentro errores en tu plantilla, estoy utilizando npm y usted pnmp eso deberías aclarar en un momento, para que tu proyecto tenga mas alcanze, ademas cuando renderizas un componente al cliene-servidor este da error.

Podrías colocar una guía de instalación porque e seguido tal cual como e aprendido yo, ah me, Olvidaba soy autónomo, entonces ese es mi inconveniente man. Espero que soluciones!!!

**Comment by DarkInventor** [comment]
haha.. my apologies for the npm install issue you faced with Easy UI.

i updated the intro + i added installation guide in it too. hope it helps :) 

have a great day ahead and happy coding with Easy UI man !!

<img width="1470" alt="Screenshot 2024-10-19 at 10 08 26 AM" src="https://github.com/user-attachments/assets/ba9f27f8-0302-4953-b161-dfcf98db0253">

**Comment by deivid2025** [comment]
.Hello, how are you Kathan, a pleasure to greet you, my name is David,
look, the error that was causing me was that in the herosection or features
section, the list gave a small hydration error, the problem was that I
couldn't display a query, do you have a group on telegram?

**Comment by deivid2025** [comment]
Now I solved it thanks to chtagpt hahaha greetings bro I would like to be
in your group I speak Spanish I am from Paraguay

**Comment by DarkInventor** [comment]
haha amigoo , i know a little spanish (tbh 3 sentences only) 

i am from Toronto. i would love to have you on easy ui discord - https://discord.gg/YszGr33b

**Comment by deivid2025** [comment]
[image: image.png]
How are you bro, check out, I'm making a tutorial video of my system that I
want to put up for sale but the design looks bad and ugly. I use Canva.
What measurements does your video have? Do you use Canva to edit the videos
or other software or platform... I'll join the discord from the cell hehe..
